//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLLibrarySystemAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountStudent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccountStudent()
        {
            this.Rent_Details = new HashSet<Rent_Details>();
        }
    
        public string stu_userName { get; set; }
        public string stu_password { get; set; }
        public string email { get; set; }
        public string stuID { get; set; }
        public string statusStuAcc { get; set; }
    
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rent_Details> Rent_Details { get; set; }
    }
}
