//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLLibrarySystemAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrator
    {
        public string userName { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public Nullable<int> posID { get; set; }
        public string statusAdminAcc { get; set; }
    
        public virtual Position Position { get; set; }
    }
}
