//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLLibrarySystemAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LibraryDBEntities : DbContext
    {
        public LibraryDBEntities()
            : base("name=LibraryDBEntities")
        {
            Configuration.LazyLoadingEnabled = false;
            Database.SetInitializer<LibraryDBEntities>(null);
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountStudent> AccountStudents { get; set; }
        public virtual DbSet<Administrator> Administrators { get; set; }
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Major> Majors { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<Rent_Details> Rent_Details { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<v_AccountAdmin> v_AccountAdmin { get; set; }
        public virtual DbSet<v_AccountAdmins> v_AccountAdmins { get; set; }
        public virtual DbSet<v_AccountStudents> v_AccountStudents { get; set; }
        public virtual DbSet<v_RentalDetailsReport> v_RentalDetailsReport { get; set; }
        public virtual DbSet<v_StudentInfo> v_StudentInfo { get; set; }
        public virtual DbSet<v_StudentManagementAPI> v_StudentManagementAPI { get; set; }
    
        public virtual ObjectResult<hl_StudentInfo_Result> hl_StudentInfo(string stuUserName)
        {
            var stuUserNameParameter = stuUserName != null ?
                new ObjectParameter("stuUserName", stuUserName) :
                new ObjectParameter("stuUserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<hl_StudentInfo_Result>("hl_StudentInfo", stuUserNameParameter);
        }
    }
}
