//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLLibrarySystemAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent_Details
    {
        public string stu_userName { get; set; }
        public string callNumber { get; set; }
        public Nullable<int> unitQuantity { get; set; }
        public Nullable<System.DateTime> issueDate { get; set; }
        public Nullable<System.DateTime> dueDate { get; set; }
        public string issueStatus { get; set; }
        public Nullable<System.DateTime> checkOutDate { get; set; }
        public Nullable<int> lateFees { get; set; }
        public Nullable<int> number_Date_Late { get; set; }
        public Nullable<int> totalFees { get; set; }
    
        public virtual AccountStudent AccountStudent { get; set; }
        public virtual Book Book { get; set; }
    }
}
