//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLLibrarySystemAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_StudentManagementAPI
    {
        public string stuID { get; set; }
        public string stuFirstName { get; set; }
        public string stuLastName { get; set; }
        public string stuAddress { get; set; }
        public Nullable<long> stuPhone { get; set; }
        public string majorID { get; set; }
        public string majorName { get; set; }
        public string stu_userName { get; set; }
        public string stu_password { get; set; }
        public string statusStuAcc { get; set; }
    }
}
